mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: true

  # URL launcher
  # url:
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # When set to `None`, URL launching will be disabled completely.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux) xdg-open
    #   - (Windows) explorer
    # launcher:
    #   program: xdg-open
    #   args: []

    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    # modifiers: Control|Shift

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# dynamic_title: false

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
shell:
  program: /usr/local/bin/tmux
  args:
    - -u

# Font configuration (changes require restart)
font:
  size: 14.0
  # The normal (roman) font face to use.
  normal:
    family: Source code for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Source code for Powerline
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Source code for Powerline
    # Style can be specified to pick a specific face.
    style: Italic

# Colors (Jellybeans)
colors:
  # Default colors
  primary:
    background: '#161616'
    foreground: '#e4e4e4'

  # Cursor volors
  cursor:
    text: '#feffff'
    cursor: '#ffb472'

  # Normal colors
  normal:
    black:   '#a3a3a3'
    red:     '#e98885'
    green:   '#a3c38b'
    yellow:  '#ffc68d'
    blue:    '#a6cae2'
    magenta: '#e7cdfb'
    cyan:    '#00a69f'
    white:   '#e4e4e4'

  # Bright colors
  bright:
    black:   '#c8c8c8'
    red:     '#ffb2b0'
    green:   '#c8e2b9'
    yellow:  '#ffe1af'
    blue:    '#bddff7'
    magenta: '#fce2ff'
    cyan:    '#0bbdb6'
    white:   '#feffff'

  # Selection colors
  selection:
    text: '#5963a2'
    background: '#f6f6f6'

old_colors:
  # Default colors
  primary:
    background: '#2c2c2c'
    foreground: '#d6d6d6'

    dim_foreground:    '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background:    '#202020' # not sure
    bright_background: '#3a3a3a' # not sure

  # Cursor colors
  cursor:
    text:   '#2c2c2c'
    cursor: '#d9d9d9'

  # Normal colors
  normal:
    black:   '#1c1c1c'
    red:     '#bc5653'
    green:   '#909d63'
    yellow:  '#ebc17a'
    blue:    '#7eaac7'
    magenta: '#aa6292'
    cyan:    '#86d3ce'
    white:   '#cacaca'

  # Bright colors
  bright:
    black:   '#636363'
    red:     '#bc5653'
    green:   '#909d63'
    yellow:  '#ebc17a'
    blue:    '#7eaac7'
    magenta: '#aa6292'
    cyan:    '#86d3ce'
    white:   '#f7f7f7'

  # Dim colors
  dim:
    black:   '#232323'
    red:     '#74423f'
    green:   '#5e6547'
    yellow:  '#8b7653'
    blue:    '#556b79'
    magenta: '#6e4962'
    cyan:    '#5c8482'
    white:   '#828282'
