shell:
  program: /bin/zsh
  args:
    - --login
    - -c
    - "tmux attach || tmux"

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

selection:
  semantic_escape_chars: ",|`|:\"' ()[]{}<>"
  save_to_clipbord: true

window:
  dimensions:
    columns: 150
    lines: 85
    padding:
      x: 0
      y: 0
    dynamic_padding: false
    decoration: full
    startup_mode: Windowed

scrolling:
  history: 0
  multiplier: 3

draw_bold_text_with_bright_colors: false

# Font configuration (changes require restart)
font:
  size: 14.0
  # The normal (roman) font face to use.
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

  normal:
    # family: Iosevka
    # family: Hack Nerd Font
    family: MesloLGS NF
    # family: Source Code Pro for Powerline
    style: Regular

  # The bold font face
  bold:
    # family: Iosevka
    # family: Hack Nerd Font
    family: MesloLGS NF
    # family: Source Code Pro for Powerline
    style: Bold

  # The italic font face
  italic:
    # family: Iosevka
    # family: Hack Nerd Font
    family: MesloLGS NF
    # family: Source Code Pro for Powerline
    style: Italic

schemes:
  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'
  base16_default_dark: &base16_default_dark
    primary:
      background: '#181818'
      foreground: '#d8d8d8'
    cursor:
      text: '#d8d8d8'
      cursor: '#d8d8d8'
    normal:
      black:   '#181818'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#d8d8d8'
    bright:
      black:   '#585858'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#f8f8f8'
  jellybeans: &jellybeans
    primary:
      background: '#161616'
      foreground: '#e4e4e4'
    # cursor:
    #   text: '#feffff'
    #   cursor: '#ffb472'
    normal:
      black:   '#a3a3a3'
      red:     '#e98885'
      green:   '#a3c38b'
      yellow:  '#ffc68d'
      blue:    '#a6cae2'
      magenta: '#e7cdfb'
      cyan:    '#00a69f'
      white:   '#e4e4e4'
    bright:
      black:   '#c8c8c8'
      red:     '#ffb2b0'
      green:   '#c8e2b9'
      yellow:  '#ffe1af'
      blue:    '#bddff7'
      magenta: '#fce2ff'
      cyan:    '#0bbdb6'
      white:   '#feffff'
    selection:
      text: '#5963a2'
      background: '#f6f6f6'
  gruvbox_light: &gruvbox_light
    primary:
      background: '#fbf1c7'
      foreground: '#3c3836'
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'
  gruvbox_dark: &gruvbox_dark
    primary:
      background: '#282828'
      foreground: '#ebdbb2'
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'
  pencil_light: &pencil_light
    primary:
      background: '0xf1f1f1'
      foreground: '0x424242'
    normal:
      black:   '0x212121'
      red:     '0xc30771'
      green:   '0x10a778'
      yellow:  '0xa89c14'
      blue:    '0x008ec4'
      magenta: '0x523c79'
      cyan:    '0x20a5ba'
      white:   '0xe0e0e0'
    bright:
      black:   '0x212121'
      red:     '0xfb007a'
      green:   '0x5fd7af'
      yellow:  '0xf3e430'
      blue:    '0x20bbfc'
      magenta: '0x6855de'
      cyan:    '0x4fb8cc'
      white:   '0xf1f1f1'
  solarized_light: &solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'
  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    cursor:
      text: '0x2E3440'
      cursor: '0xD8DEE9'
    normal:
      black: '0x3B4252'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x88C0D0'
      white: '0xE5E9F0'
    bright:
      black: '0x4C566A'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x8FBCBB'
      white: '0xECEFF4'
  papercolor_light: &papercolor_light
    # Default colors
    primary:
      background: '0xeeeeee'
      foreground: '0x878787'

    cursor:
      text: '0xeeeeee'
      cursor: '0x878787'

    # Normal colors
    normal:
      black:   '0xeeeeee'
      red:     '0xaf0000'
      green:   '0x008700'
      yellow:  '0x5f8700'
      blue:    '0x0087af'
      magenta: '0x878787'
      cyan:    '0x005f87'
      white:   '0x444444'

    # Bright colors
    bright:
      black:   '0xbcbcbc'
      red:     '0xd70000'
      green:   '0xd70087'
      yellow:  '0x8700af'
      blue:    '0xd75f00'
      magenta: '0xd75f00'
      cyan:    '0x005faf'
      white:   '0x005f87'

colors: *gruvbox_dark
