# shell:
#   program: /usr/local/bin/tmux
#   args:
#     - -u

# Font configuration (changes require restart)
font:
  size: 14.0
  # The normal (roman) font face to use.
  normal:
    family: Source Code Pro for Powerline
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Source Code Pro for Powerline
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Source Code Pro for Powerline
    # Style can be specified to pick a specific face.
    style: Italic

# Colors (Jellybeans)
colors:
  # Default colors
  primary:
    background: '#161616'
    foreground: '#e4e4e4'

  # Cursor volors
  cursor:
    text: '#feffff'
    cursor: '#ffb472'

  # Normal colors
  normal:
    black:   '#a3a3a3'
    red:     '#e98885'
    green:   '#a3c38b'
    yellow:  '#ffc68d'
    blue:    '#a6cae2'
    magenta: '#e7cdfb'
    cyan:    '#00a69f'
    white:   '#e4e4e4'

  # Bright colors
  bright:
    black:   '#c8c8c8'
    red:     '#ffb2b0'
    green:   '#c8e2b9'
    yellow:  '#ffe1af'
    blue:    '#bddff7'
    magenta: '#fce2ff'
    cyan:    '#0bbdb6'
    white:   '#feffff'

  # Selection colors
  selection:
    text: '#5963a2'
    background: '#f6f6f6'
