key_bindings:
  - { key: V, mods: Alt, action: Paste }
  - { key: C, mods: Alt, action: Copy }

# Startup directory, unset or None for home directory
working_directory: None
# Make background slightly transparent
window.opacity: 1

shell:
  program: /usr/bin/zsh
  args:
    - --login
    - -c
    - "tmux attach || tmux"

env:
  TERM: xterm-256color

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

scrolling:
  history: 0
  multiplier: 3

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

cursor:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style:
    shape: Block
    blinking: Always
  blink_interval: 500

window:
  dynamic_title: true
  dimensions:
    columns: 120
    lines: 35
  decorations: full

live_config_reload: true

# Font configuration (changes require restart)
font:
  size: 12.0
  offset:
    x: 0
    y: 0
  normal:
    family: JetBrainsMono NF
    style: Regular
  bold:
    family: JetBrainsMono NF
    style: Bold
  italic:
    family: JetBrainsMono NF
    style: Italic

schemes:
  gnome_light: &gnome_light
    primary:
      foreground: '#171421'
      background: '#ffffff'
    normal:
      black:   '#171421'
      red:     '#c01c28'
      green:   '#26a269'
      yellow:  '#a2734c'
      blue:    '#12488b'
      magenta: '#a347ba'
      cyan:    '#2aa1b3'
      white:   '#d0cfcc'
    bright:
      black:   '#5e5c64'
      red:     '#f66151'
      green:   '#33d17a'
      yellow:  '#e9ad0c'
      blue:    '#2a7bde'
      magenta: '#c061cb'
      cyan:    '#33c7de'
      white:   '#ffffff'

  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#caa9fa'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'
    bright:
      black:   '#575b70'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'

  base16_default_dark: &base16_default_dark
    primary:
      background: '#181818'
      foreground: '#d8d8d8'
    cursor:
      text: '#000000' #'#d8d8d8'
      cursor: '#ffffff' #'#d8d8d8'
    normal:
      black:   '#181818'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#d8d8d8'
    bright:
      black:   '#585858'
      red:     '#ab4642'
      green:   '#a1b56c'
      yellow:  '#f7ca88'
      blue:    '#7cafc2'
      magenta: '#ba8baf'
      cyan:    '#86c1b9'
      white:   '#f8f8f8'

  jellybeans: &jellybeans
    primary:
      background: '#161616'
      foreground: '#e4e4e4'
    normal:
      black:   '#a3a3a3'
      red:     '#e98885'
      green:   '#a3c38b'
      yellow:  '#ffc68d'
      blue:    '#a6cae2'
      magenta: '#e7cdfb'
      cyan:    '#00a69f'
      white:   '#e4e4e4'
    bright:
      black:   '#c8c8c8'
      red:     '#ffb2b0'
      green:   '#c8e2b9'
      yellow:  '#ffe1af'
      blue:    '#bddff7'
      magenta: '#fce2ff'
      cyan:    '#0bbdb6'
      white:   '#feffff'
    selection:
      text: '#5963a2'
      background: '#f6f6f6'

  gruvbox_light: &gruvbox_light
    primary:
      background: '#fbf1c7'
      foreground: '#3c3836'
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

  gruvbox_dark: &gruvbox_dark
    primary:
      background: '#282828'
      foreground: '#ebdbb2'
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

  pencil_light: &pencil_light
    primary:
      background: '0xf1f1f1'
      foreground: '0x424242'
    normal:
      black:   '0x212121'
      red:     '0xc30771'
      green:   '0x10a778'
      yellow:  '0xa89c14'
      blue:    '0x008ec4'
      magenta: '0x523c79'
      cyan:    '0x20a5ba'
      white:   '0xe0e0e0'
    bright:
      black:   '0x212121'
      red:     '0xfb007a'
      green:   '0x5fd7af'
      yellow:  '0xf3e430'
      blue:    '0x20bbfc'
      magenta: '0x6855de'
      cyan:    '0x4fb8cc'
      white:   '0xf1f1f1'

  solarized_light: &solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

  nord: &nord
    primary:
      background: '0x2E3440'
      foreground: '0xD8DEE9'
    cursor:
      text: '0x2E3440'
      cursor: '0xD8DEE9'
    normal:
      black: '0x3B4252'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x88C0D0'
      white: '0xE5E9F0'
    bright:
      black: '0x4C566A'
      red: '0xBF616A'
      green: '0xA3BE8C'
      yellow: '0xEBCB8B'
      blue: '0x81A1C1'
      magenta: '0xB48EAD'
      cyan: '0x8FBCBB'
      white: '0xECEFF4'

  papercolor_light: &papercolor_light
    primary:
      background: '0xeeeeee'
      foreground: '0x878787'
    cursor:
      text: '0xeeeeee'
      cursor: '0x878787'
    normal:
      black:   '0xeeeeee'
      red:     '0xaf0000'
      green:   '0x008700'
      yellow:  '0x5f8700'
      blue:    '0x0087af'
      magenta: '0x878787'
      cyan:    '0x005f87'
      white:   '0x444444'
    bright:
      black:   '0xbcbcbc'
      red:     '0xd70000'
      green:   '0xd70087'
      yellow:  '0x8700af'
      blue:    '0xd75f00'
      magenta: '0xd75f00'
      cyan:    '0x005faf'
      white:   '0x005f87'

  ayu_dark: &ayu_dark
    primary:
      background: '#0A0E14'
      foreground: '#B3B1AD'
    normal:
      black: '#01060E'
      red: '#EA6C73'
      green: '#91B362'
      yellow: '#F9AF4F'
      blue: '#53BDFA'
      magenta: '#FAE994'
      cyan: '#90E1C6'
      white: '#C7C7C7'
    bright:
      black: '#686868'
      red: '#F07178'
      green: '#C2D94C'
      yellow: '#FFB454'
      blue: '#59C2FF'
      magenta: '#FFEE99'
      cyan: '#95E6CB'
      white: '#FFFFFF'

  tender: &tender
    primary:
      background: '0x282828'
      foreground: '0xeeeeee'
    normal:
      black:   '0x282828'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xeeeeee'
    bright:
      black:   '0x4c4c4c'
      red:     '0xf43753'
      green:   '0xc9d05c'
      yellow:  '0xffc24b'
      blue:    '0xb3deef'
      magenta: '0xd3b987'
      cyan:    '0x73cef4'
      white:   '0xfeffff'

  nord:
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'

  cobalt2_light: &cobalt2_light
    cursor:
      text: '#fefff2'
      cursor: '#f0cc09'

    selection:
      text: '#b5b5b5'
      background: '#18354f'

    primary:
      background: '#132738'
      foreground: '#ffffff'

    normal:
      black:   '#000000'
      red:     '#ff0000'
      green:   '#38de21'
      yellow:  '#ffe50a'
      blue:    '#1460d2'
      magenta: '#ff005d'
      cyan:    '#00bbbb'
      white:   '#bbbbbb'

    bright:
      black:   '#555555'
      red:     '#f40e17'
      green:   '#3bd01d'
      yellow:  '#edc809'
      blue:    '#5555ff'
      magenta: '#ff55ff'
      cyan:    '#6ae3fa'
      white:   '#ffffff'

  spacemacs: &spacemacs
    # Default colors
    primary:
      background: '0x1f2022'
      foreground: '0xa3a3a3'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1f2022'
      cursor: '0xa3a3a3'

    # Normal colors
    normal:
      black:   '0x1f2022'
      red:     '0xf2241f'
      green:   '0x67b11d'
      yellow:  '0xb1951d'
      blue:    '0x4f97d7'
      magenta: '0xa31db1'
      cyan:    '0x2d9574'
      white:   '0xa3a3a3'

    # Bright colors
    bright:
      black:   '0x585858'
      red:     '0xf2241f'
      green:   '0x67b11d'
      yellow:  '0xb1951d'
      blue:    '0x4f97d7'
      magenta: '0xa31db1'
      cyan:    '0x2d9574'
      white:   '0xf8f8f8'

    indexed_colors:
      - { index: 16, color: '0xffa500' }
      - { index: 17, color: '0xb03060' }
      - { index: 18, color: '0x282828' }
      - { index: 19, color: '0x444155' }
      - { index: 20, color: '0xb8b8b8' }
      - { index: 21, color: '0xe8e8e8' }
  alacritty-night-owl-colors: &alacritty-night-owl-colors
    # Default colors
    primary:
      background: '0x011627'
      foreground: '0xd6deeb'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0xffffff'
      cursor: '0x7e57c2'

    # Normal colors
    normal:
      black:   '0x000000'
      red:     '0xef5350'
      green:   '0x22da6e'
      yellow:  '0xaddb67'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x21c7a8'
      white:   '0xffffff'

    # Bright colors
    bright:
      black:   '0x575656'
      red:     '0xef5350'
      green:   '0x22da6e'
      yellow:  '0xffeb95'
      blue:    '0x82aaff'
      magenta: '0xc792ea'
      cyan:    '0x7fdbca'
      white:   '0xffffff'

colors: *base16_default_dark
